### ISSUE TITLE
Timelapse sometimes won't read AVI

### ISSUE THREAD

**Issue by Warkorentin** [saulgreenberg/Timelapse#1]
We've had this behavior on multiple computers, Timelapse suddenly can't read videos if they are in AVI (from Reconnyx Hyperfire 2). There is no error, simply a black screen where the video should be. 

The problem probably comes from an update on my side, but I can't narrow it down to anything. 
Does Timelapse rely on a specific library for this particular file format ? 
Do you have an idea of what could be causing this problem ?

Thank you,

**Comment by saulgreenberg** [comment]
Go to
<https://saul.cpsc.ucalgary.ca/timelapse/pmwiki.php?n=Main.FrequentlyAskedQuestions>
Timelapse: Frequently Asked Questions — Timelapse<https://saul.cpsc.ucalgary.ca/timelapse/pmwiki.php?n=Main.FrequentlyAskedQuestions>
cpsc.ucalgary.ca<https://saul.cpsc.ucalgary.ca/timelapse/pmwiki.php?n=Main.FrequentlyAskedQuestions>
[X]<https://saul.cpsc.ucalgary.ca/timelapse/pmwiki.php?n=Main.FrequentlyAskedQuestions>
And look at the section near the bottom on video playback.  It’s a system setup issue usually. Can you let me know if one of the solutions works and if so which one?
Saul
Sent from my iPhone

On Aug 20, 2024, at 6:07 AM, CorentinK ***@***.***> wrote:

﻿
[△EXTERNAL]



We've had this behavior on multiple computers, Timelaps suddenly can't read videos if they are in AVI (from Reconnyx Hyperfire 2). There is no error, simply a black screen where the video should be.

The problem probably comes from an update on my side, but I can't narrow it down to anything.
Does Time-lapse rely on a specific library for this particular file format ?
Do you have an idea of what could be causing this problem ?

Thank you,

**Comment by Warkorentin** [comment]
Thank you !

I followed step 1 (media features) which didn't seem to work. 
And then setp 2 (K-lite). Didn't work immediatly, but after a reboot it does !

Could be k-lite, but also maybe media features took some times to redownload everything ? 

Anyway, thank you !

**Comment by saulgreenberg** [comment]
Ps feel free to contact me directly. ***@***.***
Sent from my iPhone

On Aug 20, 2024, at 7:49 AM, CorentinK ***@***.***> wrote:

﻿
[△EXTERNAL]



Thank you !

I followed step 1 (media features) which didn't seem to work.
And then setp 2 (K-lite). Didn't work immediatly, but after a reboot it does !

Could be k-lite, but also maybe media features took some times to redownload everything ?

Anyway, thank you !
